#! /bin/bash

xrandr --output eDP-1-1 --mode 1920x1080 --pos 0x0 --rotate normal
# xrandr --output eDP-1-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-0 --mode 1366x768 --pos 1920x0 --rotate normal
